name: Terraform Apply

on:
  push:
    branches:
      - 'main'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: "AWS General"
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: Terraform Init
          run: terraform init

        - name: Download Plan
          uses: actions/download-artifact@v2
          with:
            name: plan

        - name: Terraform Apply
          run: terraform apply -auto-approve